call plug#begin('~/.vim/bundle')

Plug 'sheerun/vim-polyglot'
Plug 'junegunn/fzf', { 'do': './install --bin' }
Plug 'junegunn/fzf.vim'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

call plug#end()

set number
"NETRW NAVIGATE WITH CONTROL+W P
let g:netrw_banner = 0
let g:netrw_liststyle = 3
let g:netrw_browse_split = 4
let g:netrw_altv = 1
let g:netrw_winsize = 15
"augroup ProjectDrawer
"  autocmd!
"  autocmd VimEnter * :Vexplore
"augroup END

function! VexploreToggle()
  if exists("g:netrw_buffer") && bufexists(g:netrw_buffer)
        exe "bd".g:netrw_buffer | unlet g:netrw_buffer
    else
        Vexplore | let g:netrw_buffer=bufnr("%")
  endif
endfunction

nnoremap <F5> :call VexploreToggle()<CR>

nnoremap <F6> :Rg<CR>

nnoremap <F7> :Files<CR>
nnoremap <Leader>b :Buffers<CR>
nnoremap <Leader>h :History<CR>
nnoremap <Leader>t :Tags<CR>
nnoremap <Leader>y :Btags<CR>

let g:airline#extensions#tabline#enabled = 1
set termwinsize=5x0
